language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t codecsp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codecsp/docker-react npm run test